Update ua-parser-js.d.ts
Current implementation requires import default syntax
 `import UAParser from 'ua-parser-js';`

and it is causing error 

> (46,22): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

if it is not export default in typings definition file.